# Generated by Django 5.1.1 on 2024-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
